name: iOS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  unit-tests:
    name: 🧪 Unit Tests
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Xcode Version
        run: xcodebuild -version

      - name: List Schemes
        run: xcodebuild -list

      - name: Run Unit Tests
        run: |
          xcodebuild test \
          -scheme MovieMosaic \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -only-testing:MovieMosaicTests \
          -only-testing:MovieListViewModelTests \
          -parallel-testing-enabled NO \
          -resultBundlePath UnitTestResults.xcresult


  ui-tests:
    name: 📱 UI Tests
    runs-on: self-hosted
    needs: unit-tests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run UI Tests
        run: |
          xcodebuild test \
          -scheme MovieMosaic \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 16' \
          -only-testing:MovieMosaicUITests \
          -only-testing:SearchFlowUITests \
          -parallel-testing-enabled NO \
          -resultBundlePath UITestResults.xcresult
